version: '3'
services:
    postodon:
        container_name: 'postodon'
        image: bnolet/postodon:latest
        env_file:
            - ./.env
        volumes:
            -  ./src/intros.txt:/usr/src/intros.txt
            -  ./src/content.txt:/usr/src/content.txt

        restart: always