version: '3.8'

services:
  postodon:
    container_name: postodon
    image: bnolet/postodon:latest
    ports:
      - "5001:5001"
    env_file:
      - ./.env
    volumes:
      - postodon-database:/app/database

volumes:
  postodon-database:
